# -----------------------------------------------------------------------------------------------------------
# Game ideas 
epic_games_ideas = [ 
    "Fall Guys: Ultimate Knockout - Whimsical battle royale with obstacle courses https://www.fallguys.com/",
    "Superhot - Time-bending FPS https://superhotgame.com/",
    "Brawlhalla - Free-to-play platform fighter https://brawlhalla.com/",
    "Trove - Block-based MMO with RPG elements https://trovegame.com/",
    "Hunt: Showdown - PvPvE first-person shooter https://www.huntshowdown.com/",
    "Star Wars: Squadrons - Space combat game in the Star Wars universe https://www.ea.com/games/starwars/squadrons",
    "World War 3 - Tactical FPS set in a modern conflict https://www.worldwar3.com/",
    "Dauntless - Free-to-play monster hunting action RPG https://www.epicgames.com/store/en-US/p/dauntless",
    "Ghost Recon Breakpoint - Tactical shooter with open-world gameplay https://ghost-recon.ubisoft.com/game/en-us/",
    "Battle Breakers - Turn-based RPG with heroes https://www.epicgames.com/store/en-US/p/battle-breakers",
    "EFT - Escape from Tarkov - Hardcore MMOFPS with survival elements https://www.escapefromtarkov.com/",
    "Star Trek Online - Sci-fi MMORPG set in the Star Trek universe https://store.steampowered.com/app/9900/Star_Trek_Online/",
    "Satisfactory - First-person factory building game https://www.satisfactorygame.com/",
    "Oxygen Not Included - Space colony simulation game https://store.steampowered.com/app/457140/Oxygen_Not_Included/",
    "The Forest - Survival horror game https://store.steampowered.com/app/242760/The_Forest/",
    "Bioshock: The Collection - Remastered versions of the Bioshock series https://store.steampowered.com/bundle/5425/BioShock_The_Collection/",
    "No Man's Sky - Space exploration and survival game https://www.nomanssky.com/",
    "Mordhau - Multiplayer medieval melee game https://mordhau.com/",
    "Killer Instinct - Free-to-play fighting game https://www.xbox.com/en-us/games/killer-instinct",
    "ARK: Survival Evolved - Survival game with dinosaurs https://www.playark.com/",
    "Total War: Three Kingdoms - Turn-based strategy game set in ancient China https://www.totalwar.com/games/three-kingdoms/",
    "Valheim - Survival and exploration game set in Norse mythology https://www.valheimgame.com/",
    "Rust - Multiplayer survival game https://rust.facepunch.com/",
    "ARK: Genesis - Expansion for ARK: Survival Evolved https://www.playark.com/genesis/",
    "Cyberpunk 2077 - Open-world RPG in a dystopian future https://www.cyberpunk.net/en/",
    "Monster Hunter: World - Action RPG focused on hunting monsters https://store.playstation.com/en-us/product/UP0101-CUSA08829_00-MHWORLD0000000001/",
    "Hades - Roguelike dungeon crawler https://hadesgame.com/",
    "The Outer Worlds - Action RPG set in an alternate future https://www.theouterworlds.com/",
    "Dead by Daylight - Asymmetrical horror game https://deadbydaylight.com/",
    "Control - Action-adventure game with supernatural elements https://www.controlgame.com/",
    "Metro Exodus - Story-driven FPS set in a post-apocalyptic world https://www.metrothegame.com/",
    "Ghost of Tsushima - Open-world samurai action-adventure https://www.playstation.com/en-us/games/ghost-of-tsushima/",
    "Dying Light - Open-world survival horror game https://dyinglightgame.com/",
    "Star Wars Battlefront II - Multiplayer shooter set in the Star Wars universe https://www.ea.com/games/starwars/battlefront/battlefront-ii",
    "Fallout 76 - Online multiplayer RPG set in the Fallout universe https://fallout.bethesda.net/en/",
    "Assassin's Creed Valhalla - Open-world action RPG set in the Viking era https://assassinscreed.ubisoft.com/game/en-us/valhalla",
    "For Honor - Multiplayer melee combat game https://forhonor.ubisoft.com/game/en-us/",
    "Ghost Recon Wildlands - Tactical shooter with open-world gameplay https://ghost-recon.ubisoft.com/game/en-us/",
    "The Witcher 3: Wild Hunt - Open-world RPG set in a fantasy universe https://thewitcher.com/en/witcher3",
    "Rainbow Six Siege - Tactical shooter with a focus on team strategy https://rainbow6.ubisoft.com/siege/en-us/",
    "Dark Souls III - Action RPG known for its challenging gameplay https://en.bandainamcoent.eu/dark-souls/dark-souls-iii",
    "Sekiro: Shadows Die Twice - Action-adventure game set in Sengoku period Japan https://sekiro.sonypictures.com/",
    "Half-Life: Alyx - VR first-person shooter set in the Half-Life universe https://www.half-life.com/alyx/",
    "GTA Online - Open-world multiplayer game set in the Grand Theft Auto universe https://www.rockstargames.com/games/V",
    "Fortnite Creative - Build and design your own games in Fortnite https://www.epicgames.com/fortnite/en-US/creative",
    "Sea of Thieves - Multiplayer pirate adventure game https://www.seaofthieves.com/",
    "Planetside 2 - Massively multiplayer online shooter https://www.planetside2.com/",
    "Elite Dangerous - Space exploration and trading game https://www.elitedangerous.com/",
    "FIFA 21 - Football simulation game https://www.ea.com/games/fifa/fifa-21",
    "Madden NFL 21 - American football simulation game https://www.ea.com/games/madden-nfl/madden-nfl-21",
    "NBA 2K21 - Basketball simulation game https://www.2k.com/games/nba-2k/",
    "Riders Republic - Open-world sports game with extreme sports https://www.ubisoft.com/en-us/game/riders-republic",
    "Watch Dogs: Legion - Open-world action-adventure game set in London https://watchdogs.ubisoft.com/en-us/",
    "CyberConnect2 - Action RPG with immersive storytelling https://www.cyberconnect2.com/en/",
    "Hollow Knight - Metroidvania action-adventure game https://hollowknight.com/",
    "Dishonored 2 - Stealth action-adventure game https://dishonored.bethesda.net/",
    "The Evil Within - Survival horror game https://theevilwithin.bethesda.net/",
    "Final Fantasy XIV - MMORPG set in the Final Fantasy universe https://na.finalfantasyxiv.com/",
    "The Elder Scrolls V: Skyrim - Open-world RPG set in a fantasy universe https://elderscrolls.bethesda.net/",
    "Tales of Arise - Action RPG with a compelling story https://talesofrise.talesofseries.com/",
    "Ni no Kuni II: Revenant Kingdom - Action RPG with beautiful animation https://niokuni.bandaigames.eu/",
    "Persona 5 Strikers - Action RPG set in the Persona universe https://atlus.com/p5s/",
    "Darkest Dungeon - Turn-based RPG with a gothic horror theme https://darkestdungeon.com/",
    "XCOM 2 - Turn-based strategy game set in a sci-fi universe https://xcom.com/",
    "Civilization VI - Turn-based strategy game focused on building an empire https://civilization.com/",
    "Stardew Valley - Farming simulation game https://www.stardewvalley.net/",
    "Hades - Roguelike dungeon crawler with a Greek mythology theme https://hadesgame.com/",
    "Undertale - Indie RPG with unique storytelling and mechanics https://undertale.com/",
    "The Binding of Isaac: Rebirth - Roguelike dungeon crawler https://bindingofisaac.com/",
    "Cuphead - Run-and-gun game with a vintage cartoon style https://cupheadgame.com/",
    "Enter the Gungeon - Bullet hell dungeon crawler https://dodgegun.com/",
    "Celeste - Platformer about climbing a mountain https://title.shelly.s3.amazonaws.com/celeste/",
    "Slay the Spire - Deck-building roguelike https://www.slaythespire.com/",
    "Darkwood - Survival horror game with a top-down perspective https://www.darkwoodgame.com/",
    "Risk of Rain 2 - Roguelike third-person shooter https://riskofrain.com/",
    "A Plague Tale: Innocence - Story-driven adventure game https://www.aplaguetale.com/",
    "Little Nightmares II - Puzzle-platformer with horror elements https://www.littlenightmares.com/",
    "Amnesia: The Dark Descent - Survival horror game https://amnesiagame.com/",
    "Outlast - Survival horror game set in an abandoned asylum https://outlast.brownsteinmedia.com/",
    "Layers of Fear - Psychological horror game https://www.layersoffear.com/",
    "Resident Evil 2 Remake - Survival horror game https://www.residentevil.com/resident_evil_2/",
    "Dead Space - Sci-fi survival horror game https://www.ea.com/games/dead-space/dead-space",
    "The Last of Us Part II - Action-adventure game with a gripping narrative https://www.thelastofus.playstation.com/",
    "God of War - Action-adventure game based on Norse mythology https://www.playstation.com/en-us/games/god-of-war/",
    "Monster Hunter Rise - Action RPG focused on hunting monsters https://monsterhunterrise.com/",
    "Bloodborne - Action RPG with gothic horror elements https://bloodborne.playstation.com/",
    "Sekiro: Shadows Die Twice - Action-adventure game with stealth mechanics https://sekiro.shadowsdie.twice/",
    "Ghost of Tsushima - Open-world action-adventure game set in feudal Japan https://www.playstation.com/en-us/games/ghost-of-tsushima/",
    "Red Dead Redemption 2 - Open-world action-adventure game set in the Wild West https://www.rockstargames.com/games/reddeadredemption2",
    "Forza Horizon 4 - Open-world racing game https://www.forzamotorsport.net/en-us/games/fh4",
    "Gran Turismo Sport - Realistic racing simulation game https://www.gran-turismo.com/us/gtsport/",
    "Assetto Corsa - Racing simulator focused on realism https://www.assettocorsa.net/",
    "Need for Speed Heat - Racing game with an open-world environment https://www.ea.com/games/need-for-speed/need-for-speed-heat",
    "F1 2021 - Formula 1 racing simulation game https://www.codemasters.com/f1-2021/",
    "TrackMania - Arcade racing game with track-building elements https://www.trackmania.com/",
    "Mario Kart 8 Deluxe - Racing game featuring Mario characters https://mariokart8.nintendo.com/",
    "Wreckfest - Racing game with vehicle destruction mechanics https://www.bugbeargames.com/wreckfest/",
    "Dirt 5 - Off-road racing game https://www.codemasters.com/dirt-5/",
    "Burnout Paradise Remastered - Open-world racing game https://www.ea.com/games/burnout/burnout-paradise-remastered",
    "Riders Republic - Open-world extreme sports game https://www.ubisoft.com/en-us/game/riders-republic",
    "Tony Hawk's Pro Skater 1 + 2 - Remastered skateboarding game https://www.tonyhawksproskater.com/",
    "Just Cause 4 - Open-world action-adventure game https://www.justcause.com/en-us/",
    "Far Cry 5 - Open-world first-person shooter https://far-cry.ubisoft.com/en-us/games/far-cry-5/",
    "Watch Dogs 2 - Open-world action-adventure game focused on hacking https://watchdogs.ubisoft.com/en-us/",
    "Dragon Age: Inquisition - Action RPG with an expansive world https://dragonage.bioware.com/inquisition/",
    "Dark Souls Remastered - Updated version of the classic action RPG https://en.bandainamcoent.eu/dark-souls/dark-souls-remastered",
    "Bloodstained: Ritual of the Night - Metroidvania game inspired by Castlevania https://bloodstained RitualoftheNight.com/",
    "The Legend of Zelda: Breath of the Wild - Open-world action-adventure game https://www.zelda.com/breath-of-the-wild/",
    "Super Smash Bros. Ultimate - Platform fighting game featuring various Nintendo characters https://www.smashbros.com/",
    "Fallout 4 - Open-world RPG set in a post-apocalyptic universe https://fallout.bethesda.net/en/",
    "Darkest Dungeon II - Sequel to the popular roguelike dungeon crawler https://darkestdungeon.com/",
    "Outer Wilds - Space exploration game with a time loop mechanic https://www.mobiusdigitalgames.com/outerwilds",
    "No More Heroes III - Action-adventure game with a quirky narrative https://www.nmtheory.com/",
    "The Stanley Parable: Ultra Deluxe - Narrative-driven game with humor https://www.stanleyparable.com/",
    "Cyberpunk 2077 - Open-world RPG set in a dystopian future https://www.cyberpunk.net/en/",
    "Assassin's Creed Odyssey - Action RPG set in ancient Greece https://assassinscreed.ubisoft.com/game/en-us/odyssey",
    "Ghost of Tsushima - Open-world action-adventure game set in feudal Japan https://www.playstation.com/en-us/games/ghost-of-tsushima/",
    "Valhalla - Action RPG based on Norse mythology https://valhallagame.com/",
    "A Plague Tale: Requiem - Sequel to the story-driven adventure game https://www.aplaguetale.com/",
    "Remnant: From the Ashes - Co-op third-person shooter with RPG elements https://www.remnantgame.com/",
    "Sea of Thieves - Multiplayer pirate adventure game https://www.seaofthieves.com/",
    "Monster Hunter World: Iceborne - Expansion for Monster Hunter World https://www.monsterhunter.com/world-iceborne/",
    "Shadow of the Tomb Raider - Action-adventure game featuring Lara Croft https://tombraider.com/",
    "Middle-earth: Shadow of War - Action RPG set in the Lord of the Rings universe https://shadowofwar.com/",
    "Far Cry 6 - Open-world first-person shooter https://far-cry.ubisoft.com/en-us/games/far-cry-6/",
    "Wasteland 3 - RPG set in a post-apocalyptic world https://wasteland3.com/",
    "Divinity: Original Sin II - Critically acclaimed RPG https://divinity.game/",
    "The Outer Worlds - Action RPG with a rich narrative https://theouterworlds.com/",
    "CyberConnect2 - Action RPG with immersive storytelling https://www.cyberconnect2.com/en/",
    "Fallout: New Vegas - Post-apocalyptic RPG known for its storytelling https://fallout.bethesda.net/en/",
    "Yakuza: Like a Dragon - RPG with a mix of action and turn-based combat https://yakuza.sega.com/likeadragon/",
    "Persona 5 Royal - Enhanced version of the acclaimed RPG https://atlus.com/p5r/",
    "Bravely Default II - RPG with a classic turn-based combat system https://www.bravelydefault2.com/",
    "Chrono Trigger - Classic time-traveling RPG https://www.chronotrigger.com/",
    "Hollow Knight: Silksong - Sequel to the beloved indie game https://hollowknight.com/",
    "Fire Emblem: Three Houses - Tactical RPG with a rich narrative https://fireemblem.fandom.com/wiki/Fire_Emblem:_Three_Houses",
    "Stardew Valley - Indie farming simulation game https://www.stardewvalley.net/",
    "Hades - Roguelike dungeon crawler with an engaging story https://hadesgame.com/",
    "Celeste - Indie platformer about climbing a mountain https://title.shelly.s3.amazonaws.com/celeste/",
    "Undertale - Indie RPG with unique mechanics and storytelling https://undertale.com/",
    "Octopath Traveler - RPG with a retro art style and turn-based combat https://www.octopathtraveler.com/",
    "Xenoblade Chronicles 2 - Open-world JRPG with an engaging story https://www.nintendo.com/games/detail/xenoblade-chronicles-2-switch/",
    "Final Fantasy VII Remake - Reimagining of the classic RPG https://ffvii-remake.square-enix-games.com/en-us/",
    "Dark Souls Remastered - Updated version of the classic action RPG https://en.bandainamcoent.eu/dark-souls/dark-souls-remastered",
    "Nioh 2 - Action RPG with a focus on samurai combat https://www.playstation.com/en-us/games/nioh-2/",
    "Sekiro: Shadows Die Twice - Action-adventure game with a focus on stealth https://sekiro.shadowsdie.twice/",
    "The Witcher 3: Wild Hunt - Open-world RPG with an expansive story https://thewitcher.com/en/witcher3",
    "Ghost of Tsushima - Open-world action-adventure game set in feudal Japan https://www.playstation.com/en-us/games/ghost-of-tsushima/",
    "The Legend of Zelda: Breath of the Wild - Open-world adventure game https://www.zelda.com/breath-of-the-wild/",
    "Red Dead Redemption 2 - Open-world action-adventure game set in the Wild West https://www.rockstargames.com/games/reddeadredemption2",
    "Minecraft - Sandbox game focused on building and survival https://www.minecraft.net/",
    "Terraria - 2D sandbox adventure game https://www.terraria.org/",
    "Don't Starve - Survival game with a unique art style https://www.klei.com/games/dont-starve",
    "Subnautica - Open-world survival game set underwater https://subnautica.com/",
    "The Long Dark - Survival game set in the Canadian wilderness https://thelongdark.com/",
    "Hollow Knight - Metroidvania action-adventure game https://hollowknight.com/",
    "Celeste - Platformer about climbing a mountain https://title.shelly.s3.amazonaws.com/celeste/",
    "Apex Legends - Free-to-play battle royale with unique characters https://www.ea.com/games/apex-legends",
    "Valorant - Tactical shooter with hero-based gameplay https://playvalorant.com/",
    "Fortnite - Battle royale with building mechanics https://www.epicgames.com/fortnite/en-US/home",
    "Call of Duty: Warzone - Free-to-play battle royale game https://www.callofduty.com/warzone",
    "Genshin Impact - Open-world action RPG with gacha mechanics https://genshin.hoyoverse.com/en/home",
    "Rainbow Six Siege - Tactical FPS focused on team strategy https://www.ubisoft.com/en-us/game/rainbow-six/siege",
    "Counter-Strike: Global Offensive - Tactical first-person shooter https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/",
    "Team Fortress 2 - Team-based shooter with unique classes https://store.steampowered.com/app/440/Team_Fortress_2/",
    "Overwatch - Hero shooter with team-based objectives https://playoverwatch.com/",
    "Dead by Daylight - Asymmetrical multiplayer horror game https://deadbydaylight.com/",
    "Phasmophobia - Co-op horror game focused on ghost hunting https://store.steampowered.com/app/739630/Phasmophobia/",
    "Among Us - Social deduction game with friends https://www.innersloth.com/gameAmongUs.php",
    "Fall Guys - Multiplayer party game with obstacle courses https://fallguys.com/",
    "Minecraft Dungeons - Dungeon crawler based on Minecraft https://www.minecraft.net/en-us/about-minecraft-dungeons",
    "Ark: Survival Evolved - Survival game set in a prehistoric world https://www.arkgame.com/",
    "Subnautica: Below Zero - Underwater survival game in a frozen world https://subnautica.com/below-zero/",
    "Ghost of Tsushima - Open-world action-adventure game set in feudal Japan https://www.playstation.com/en-us/games/ghost-of-tsushima/",
    "Monster Hunter World - Action RPG focused on hunting monsters https://monsterhunterworld.com/",
    "Hades - Roguelike dungeon crawler with an engaging story https://hadesgame.com/",
    "The Outer Worlds - Action RPG with a rich narrative https://theouterworlds.com/",
    "Fire Emblem: Three Houses - Tactical RPG with a deep narrative https://fireemblem.fandom.com/wiki/Fire_Emblem:_Three_Houses",
    "Final Fantasy XIV - MMORPG with an expansive world https://www.finalfantasyxiv.com/",
    "World of Warcraft - Iconic MMORPG with a vast world https://worldofwarcraft.com/en-us/",
    "Monster Hunter Generations Ultimate - Action RPG focused on hunting monsters https://monsterhunterworld.com/",
    "Dark Souls III - Action RPG known for its difficulty https://en.bandainamcoent.eu/dark-souls/dark-souls-iii",
    "Sekiro: Shadows Die Twice - Action-adventure game with stealth mechanics https://sekiro.shadowsdie.twice/",
    "Destiny 2 - Online action MMO with rich lore https://www.bungie.net/7/en/Destiny/NewLight",
    "Halo: The Master Chief Collection - Collection of Halo games https://www.xbox.com/en-us/games/store/halo-the-master-chief-collection/9pvl9dd8h2xz",
    "Rainbow Six: Siege - Tactical FPS with team-based gameplay https://www.ubisoft.com/en-us/game/rainbow-six/siege",
    "FIFA 22 - Soccer simulation game https://www.ea.com/games/fifa/fifa-22",
    "Madden NFL 22 - American football simulation game https://www.ea.com/games/madden-nfl/madden-nfl-22",
    "NBA 2K22 - Basketball simulation game https://www.nba.com/2k/",
    "The Sims 4 - Life simulation game https://www.ea.com/games/the-sims/the-sims-4",
    "Stardew Valley - Indie farming simulation game https://www.stardewvalley.net/",
    "Terraria - 2D sandbox adventure game https://www.terraria.org/",
    "Cities: Skylines - City-building simulation game https://www.paradoxinteractive.com/games/cities-skylines/",
    "Planet Coaster - Theme park simulation game https://www.planetcoaster.com/",
    "Microsoft Flight Simulator - Realistic flight simulation game https://www.flightsimulator.com/",
    "Kerbal Space Program - Spaceflight simulation game https://www.kerbalspaceprogram.com/",
    "No Man's Sky - Open-world space exploration game https://www.nomanssky.com/",
    "Factorio - Automation and factory-building game https://factorio.com/",
    "Cities: Skylines - City-building simulation game https://www.paradoxinteractive.com/games/cities-skylines/",
    "Planet Coaster - Theme park simulation game https://www.planetcoaster.com/",
    "Two Point Hospital - Hospital management simulation game https://www.twopointhospital.com/",
    "RimWorld - Colony simulation game https://rimworld.com/",
    "Farming Simulator 22 - Farming simulation game https://www.farming-simulator.com/",
    "Sims 4 - Life simulation game https://www.ea.com/games/the-sims/the-sims-4/",
    "Project Zomboid - Zombie survival simulation game https://projectzomboid.com/",
    "Phasmophobia - Asymmetrical horror multiplayer game https://store.steampowered.com/app/739630/Phasmophobia/",
    "Raft - Survival game set on the ocean https://raft.itch.io/raft",
    "Satisfactory - Factory building and automation game https://satisfactorygame.com/",
    "House Flipper - Home renovation simulation game https://houseflippergame.com/",
    "The Forest - Survival game set in a forest after a plane crash https://theforestgame.com/",
    "This War of Mine - Survival game focusing on civilian experience in war https://thiswarofmine.com/",
    "Banished - City-building strategy game https://www.shiningrocksoftware.com/banished/"
]

steam_game_ideas = [
    "Team Fortress 2 - Classic team-based shooter https://store.steampowered.com/app/440/Team_Fortress_2/",
    "Dota 2 - Multiplayer online battle arena (MOBA) https://store.steampowered.com/app/570/Dota_2/",
    "Counter-Strike: Global Offensive - First-person shooter https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/",
    "Warframe - Sci-fi cooperative shooter https://store.steampowered.com/app/230410/Warframe/",
    "Apex Legends - Battle royale with unique heroes https://store.steampowered.com/app/1172470/Apex_Legends/",
    "Destiny 2 - Action MMO with rich lore https://store.steampowered.com/app/1085660/Destiny_2/",
    "Paladins - Hero-based shooter https://store.steampowered.com/app/444090/Paladins/",
    "Path of Exile - Dark fantasy action RPG https://store.steampowered.com/app/238960/Path_of_Exile/",
    "Brawlhalla - Platform fighter https://store.steampowered.com/app/291550/Brawlhalla/",
    "Realm Royale - Fantasy battle royale https://store.steampowered.com/app/813820/Realm_Royale/",
    "Unturned - Zombie survival sandbox https://store.steampowered.com/app/304930/Unturned/",
    "Star Wars: The Old Republic - Sci-fi MMORPG https://www.swtor.com/",
    "Rogue Company - Third-person tactical shooter https://www.epicgames.com/store/en-US/p/rogue-company",
    "Deceit - Social deduction FPS https://store.steampowered.com/app/466240/Deceit/",
    "SMITE - Third-person MOBA https://store.steampowered.com/app/386360/SMITE/",
    "Fallout Shelter - Vault simulation game https://store.steampowered.com/app/588430/Fallout_Shelter/",
    "Helltaker - Puzzle adventure game https://store.steampowered.com/app/1289310/Helltaker/",
    "VRChat - Virtual social experience https://store.steampowered.com/app/438100/VRChat/",
    "Yu-Gi-Oh! Duel Links - Card dueling game https://store.steampowered.com/app/601510/YuGiOh_Duel_Links/",
    "Fishing Planet - Realistic fishing simulator https://store.steampowered.com/app/380600/Fishing_Planet/",
    "EVE Online - Space MMORPG https://store.steampowered.com/app/8500/EVE_Online/",
    "SCP: Secret Laboratory - Multiplayer horror game https://store.steampowered.com/app/700330/SCP_Secret_Laboratory/",
    "Crusader Kings II - Historical strategy game https://store.steampowered.com/app/203770/Crusader_Kings_II/",
    "Dauntless - Monster hunting RPG https://www.epicgames.com/store/en-US/p/dauntless",
    "Idle Champions of the Forgotten Realms - D&D-inspired idle game https://store.steampowered.com/app/627690/Idle_Champions_of_the_Forgotten_Realms/",
    "Neverwinter - Action MMORPG in the D&D universe https://store.steampowered.com/app/109600/Neverwinter/",
    "Doki Doki Literature Club! - Visual novel psychological horror https://store.steampowered.com/app/698780/Doki_Doki_Literature_Club/",
    "Muck - Survival roguelike https://store.steampowered.com/app/1625450/Muck/",
    "Magic: The Gathering Arena - Digital card game https://magic.wizards.com/en/mtgarena",
    "SpellForce 3: Versus Edition - RTS/RPG hybrid https://store.steampowered.com/app/1416260/SpellForce_3_Versus_Edition/",
    "TrackMania Nations Forever - Arcade racing game https://store.steampowered.com/app/11020/TrackMania_Nations_Forever/",
    "War Thunder - WWII military vehicle combat https://store.steampowered.com/app/236390/War_Thunder/",
    "Planetside 2 - Massive online shooter https://store.steampowered.com/app/218230/PlanetSide_2/",
    "Hades - Rogue-like dungeon crawler with an engaging story https://store.steampowered.com/app/1145360/Hades/",
    "Ghostrunner - Fast-paced first-person action game set in a cyberpunk world https://store.steampowered.com/app/743130/Ghostrunner/",
    "Dead Cells - A rogue-lite, metroidvania-inspired action-platformer https://store.steampowered.com/app/588650/Dead_Cells/",
    "Sekiro: Shadows Die Twice - An action-adventure game with stealth mechanics set in Sengoku period Japan https://store.steampowered.com/app/814380/Sekiro_Shadows_Die_Twice/",
    "Assassin's Creed Odyssey - Action RPG set in ancient Greece during the Peloponnesian War https://store.steampowered.com/app/812140/Assassins_Creed_Odyssey/",
    "Red Dead Redemption 2 - Open-world action-adventure game set in the Wild West https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/",
    "Cyberpunk 2077 - Open-world RPG set in a dystopian future https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
    "The Witcher 3: Wild Hunt - Open-world RPG with a rich narrative and expansive world https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
    "Half-Life: Alyx - VR game set in the Half-Life universe https://store.steampowered.com/app/546560/HalfLife_Alyx/",
    "Monster Hunter: World - Action RPG focused on hunting monsters https://store.steampowered.com/app/582010/Monster_Hunter_World/",
    "Celeste - Platformer about climbing a mountain with tight controls and great narrative https://store.steampowered.com/app/504230/Celeste/",
    "Stardew Valley - Indie farming simulation game where you build a farm and interact with villagers https://store.steampowered.com/app/413150/Stardew_Valley/",
    "Terraria - 2D sandbox adventure game that lets you explore, craft, and build https://store.steampowered.com/app/105600/Terraria/",
    "Cities: Skylines - City-building simulation game that lets you design and manage a city https://store.steampowered.com/app/255710/Cities_Skylines/",
    "Planet Coaster - Theme park simulation game where you build and manage a theme park https://store.steampowered.com/app/493340/Planet_Coaster/",
    "Microsoft Flight Simulator - Realistic flight simulation game with stunning graphics https://store.steampowered.com/app/1250410/Microsoft_Flight_Simulator/",
    "Kerbal Space Program - Spaceflight simulation game where you build and manage a space program https://store.steampowered.com/app/220200/Kerbal_Space_Program/",
    "No Man's Sky - Open-world space exploration game with procedural generation https://store.steampowered.com/app/275850/No_Mans_Sky/",
    "Factorio - Automation and factory-building game https://store.steampowered.com/app/427520/Factorio/",
    "Two Point Hospital - Hospital management simulation game where you build and manage a hospital https://store.steampowered.com/app/535930/Two_Point_Hospital/",
    "RimWorld - Colony simulation game that tells a story based on your choices https://store.steampowered.com/app/294100/RimWorld/",
    "Farming Simulator 22 - Farming simulation game that offers realistic farming experiences https://store.steampowered.com/app/1604020/Farming_Simulator_22/",
    "Project Zomboid - Zombie survival simulation game where you must manage resources and survive https://store.steampowered.com/app/108600/Project_Zomboid/",
    "Phasmophobia - Asymmetrical horror multiplayer game focused on ghost hunting https://store.steampowered.com/app/739630/Phasmophobia/",
    "Raft - Survival game set on the ocean where you gather resources to survive https://store.steampowered.com/app/648450/Raft/",
    "Satisfactory - Factory building and automation game in a first-person perspective https://store.steampowered.com/app/526870/Satisfactory/",
    "House Flipper - Home renovation simulation game where you buy and renovate properties https://store.steampowered.com/app/613100/House_Flipper/",
    "The Forest - Survival game set in a forest after a plane crash https://store.steampowered.com/app/242760/The_Forest/",
    "This War of Mine - Survival game focusing on civilian experiences in war https://store.steampowered.com/app/282070/This_War_of_Mine/",
    "Banished - City-building strategy game with a focus on resource management https://store.steampowered.com/app/242920/Banished/",
    "Hollow Knight - Action-adventure game with a beautiful hand-drawn world https://store.steampowered.com/app/367520/Hollow_Knight/",
    "Cuphead - Run and gun indie game with a unique art style inspired by 1930s cartoons https://store.steampowered.com/app/268910/Cuphead/",
    "Portal 2 - Puzzle-platform game that combines humor and brain-bending puzzles https://store.steampowered.com/app/620/Portal_2/",
    "Limbo - Indie puzzle-platformer known for its dark atmosphere and story https://store.steampowered.com/app/48000/Limbo/",
    "Inside - A narrative-driven puzzle-platformer with dark themes https://store.steampowered.com/app/480490/INSIDE/",
    "Dead by Daylight - Asymmetrical horror game where one player is the killer https://store.steampowered.com/app/381210/Dead_by_Daylight/",
    "Among Us - Social deduction game where players work together to find the imposter https://store.steampowered.com/app/945360/Among_Us/",
    "Rust - Multiplayer survival game focused on resource gathering and base building https://store.steampowered.com/app/252490/Rust/",
    "ARK: Survival Evolved - Open-world survival game featuring dinosaurs https://store.steampowered.com/app/346110/ARK_Survival_Evolved/",
    "The Binding of Isaac: Rebirth - Roguelike dungeon crawler with dark themes and humor https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/",
    "Enter the Gungeon - Bullet-hell dungeon crawler with roguelike elements https://store.steampowered.com/app/311590/Enter_the_Gungeon/",
    "Slay the Spire - Deck-building roguelike that combines card games with dungeon crawling https://store.steampowered.com/app/646570/Slay_the_Spire/",
    "Stardew Valley - Farming simulation game where you build a farm and interact with villagers https://store.steampowered.com/app/413150/Stardew_Valley/",
    "Dying Light - Open-world zombie survival game with parkour mechanics https://store.steampowered.com/app/239140/Dying_Light/",
    "The Elder Scrolls V: Skyrim - Open-world RPG set in a fantasy world filled with dragons https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim/",
    "Fallout 4 - Open-world RPG set in a post-apocalyptic world https://store.steampowered.com/app/377160/Fallout_4/",
    "Shadow of the Tomb Raider - Action-adventure game featuring the iconic character Lara Croft https://store.steampowered.com/app/750920/Shadow_of_the_Tomb_Raider/",
    "Dark Souls III - Action RPG known for its challenging gameplay and intricate lore https://store.steampowered.com/app/374320/DARK_SOULS_III/",
    "Nioh - Action RPG set in a dark fantasy version of the Sengoku period Japan https://store.steampowered.com/app/1245620/NIOH_2/",
    "Sekiro: Shadows Die Twice - An action-adventure game with stealth mechanics set in Sengoku period Japan https://store.steampowered.com/app/814380/Sekiro_Shadows_Die_Twice/",
    "Monster Hunter: World - Action RPG focused on hunting monsters https://store.steampowered.com/app/582010/Monster_Hunter_World/",
    "ARK: Survival Evolved - Open-world survival game featuring dinosaurs https://store.steampowered.com/app/346110/ARK_Survival_Evolved/",
    "War Thunder - Military vehicle combat game set in WWII https://store.steampowered.com/app/236390/War_Thunder/",
    "World of Tanks - Free-to-play online tank battle game https://store.steampowered.com/app/1094520/World_of_Tanks/",
    "World of Warships - Naval combat game featuring historic naval battles https://store.steampowered.com/app/552990/World_of_Warships/",
    "Garry's Mod - Sandbox game that allows you to create and manipulate objects https://store.steampowered.com/app/4000/Garrys_Mod/",
    "Terraria - 2D sandbox adventure game that lets you explore, craft, and build https://store.steampowered.com/app/105600/Terraria/",
    "Hollow Knight - Action-adventure game with a beautiful hand-drawn world https://store.steampowered.com/app/367520/Hollow_Knight/",
    "Slime Rancher - A charming farming simulation game where you collect and raise slimes https://store.steampowered.com/app/390810/Slime_Rancher/",
    "Oxygen Not Included - Space-colony simulation game where you manage resources and keep your colonists alive https://store.steampowered.com/app/457140/Oxygen_Not_Included/",
    "Spelunky 2 - Challenging roguelike platformer where you explore caves and collect treasures https://store.steampowered.com/app/418530/Spelunky_2/",
    "Cuphead - Run and gun indie game with a unique art style inspired by 1930s cartoons https://store.steampowered.com/app/268910/Cuphead/",
    "Worms W.M.D - Turn-based strategy game with a humorous twist https://store.steampowered.com/app/327030/Worms_W_M_D/",
    "Farming Simulator 19 - Farming simulation game that offers realistic farming experiences https://store.steampowered.com/app/447020/Farming_Simulator_19/",
    "Factorio - Automation and factory-building game https://store.steampowered.com/app/427520/Factorio/",
    "Cities: Skylines - City-building simulation game that lets you design and manage a city https://store.steampowered.com/app/255710/Cities_Skylines/",
    "Farming Simulator 22 - Farming simulation game that offers realistic farming experiences https://store.steampowered.com/app/1604020/Farming_Simulator_22/",
    "RimWorld - Colony simulation game that tells a story based on your choices https://store.steampowered.com/app/294100/RimWorld/",
    "Planet Coaster - Theme park simulation game where you build and manage a theme park https://store.steampowered.com/app/493340/Planet_Coaster/",
    "The Forest - Survival game set in a forest after a plane crash https://store.steampowered.com/app/242760/The_Forest/",
    "This War of Mine - Survival game focusing on civilian experiences in war https://store.steampowered.com/app/282070/This_War_of_Mine/",
    "Banished - City-building strategy game with a focus on resource management https://store.steampowered.com/app/242920/Banished/",
    "Ghost Recon Breakpoint - Tactical shooter set in an open world https://store.steampowered.com/app/752170/Tom_Clancys_Ghost_Recon_Breakpoint/",
    "Metal Gear Solid V: The Phantom Pain - Action-adventure stealth game with an open world https://store.steampowered.com/app/287700/Metal_Gear_Solid_V_The_Phantom_Pain/",
    "Far Cry 5 - Open-world first-person shooter set in Montana https://store.steampowered.com/app/552520/Far_Cry_5/",
    "Assassin's Creed Valhalla - Action RPG set in the Viking Age https://store.steampowered.com/app/581320/Assassins_Creed_Valhalla/",
    "Watch Dogs: Legion - Action-adventure game set in a near-future London https://store.steampowered.com/app/981370/Watch_Dogs_Legion/",
    "Hitman 3 - Stealth game that lets you become a master assassin https://store.steampowered.com/app/584650/Hitman_3/",
    "The Dark Pictures Anthology: Man of Medan - Interactive horror game that is part of an anthology series https://store.steampowered.com/app/390240/The_Dark_Pictures_Anthology_Man_of_Medan/",
    "Little Nightmares II - Puzzle-platformer horror game that serves as a prequel to the first game https://store.steampowered.com/app/728020/Little_Nightmares_II/",
    "Resident Evil 2 - Survival horror game and remake of the 1998 classic https://store.steampowered.com/app/952060/Resident_Evil_2/",
    "Dying Light 2 - Open-world zombie survival game with parkour mechanics https://store.steampowered.com/app/534380/Dying_Light_2_Stay_Human/",
    "Ghost of Tsushima - Action-adventure game set in feudal Japan, focusing on samurai and stealth mechanics https://store.steampowered.com/app/262394/Ghost_of_Tsushima/",
    "Final Fantasy XIV - MMORPG with a rich narrative and expansive world https://store.steampowered.com/app/39210/FINAL_FANTASY_XIV_Online/",
    "Elden Ring - Open-world action RPG set in a dark fantasy world https://store.steampowered.com/app/1245620/Elden_Ring/",
    "The Elder Scrolls Online - MMORPG set in the Elder Scrolls universe https://store.steampowered.com/app/306130/The_Elder_Scrolls_Online/",
    "CyberConnect2's FFXV - Action RPG that takes place in the Final Fantasy universe https://store.steampowered.com/app/246200/FINAL_FANTASY_XV/",
    "The Outer Worlds - Action RPG set in a retro-futuristic space setting https://store.steampowered.com/app/578650/The_Outer_Worlds/",
    "Fallout: New Vegas - Action RPG set in a post-apocalyptic world https://store.steampowered.com/app/22380/Fallout_New_Vegas/",
    "Persona 5 Strikers - Action RPG sequel to Persona 5 https://store.steampowered.com/app/1389010/Persona_5_Strikers/",
    "XCOM 2 - Turn-based strategy game where you fight against an alien occupation of Earth https://store.steampowered.com/app/268500/XCOM_2/",
    "Civilization VI - Turn-based strategy game where you build an empire and compete against others https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/",
    "Total War: Three Kingdoms - Strategy game set in ancient China during the Three Kingdoms period https://store.steampowered.com/app/779340/Total_War_Three_Kingdoms/",
    "Warhammer 40,000: Dawn of War III - Real-time strategy game set in the Warhammer 40K universe https://store.steampowered.com/app/285620/Warhammer_40000_Dawn_of_War_III/",
    "Starcraft II - Real-time strategy game set in a sci-fi universe https://starcraft2.com/",
    "Company of Heroes 2 - Real-time strategy game set in WWII https://store.steampowered.com/app/231430/Company_of_Heroes_2/",
    "Crusader Kings III - Grand strategy game focusing on dynasty management https://store.steampowered.com/app/1158310/Crusader_Kings_III/",
    "Hearts of Iron IV - WWII strategy game that lets you control a nation during the war https://store.steampowered.com/app/394360/Hearts_of_Iron_IV/",
    "Age of Empires IV - Real-time strategy game set in historical periods https://store.steampowered.com/app/813780/Age_of_Empires_IV/",
    "Warframe - Sci-fi cooperative shooter with a focus on agile combat https://store.steampowered.com/app/230410/Warframe/",
    "Dota Underlords - Auto-battler game set in the Dota universe https://store.steampowered.com/app/1046620/Dota_Underlords/",
    "Teamfight Tactics - Auto-battler game set in the League of Legends universe https://tft.leagueoflegends.com/",
    "SpellForce 3 - Action RPG and RTS hybrid https://store.steampowered.com/app/1416260/SpellForce_3_Versus_Edition/",
    "Wasteland 3 - Post-apocalyptic RPG with strategic combat https://store.steampowered.com/app/719040/Wasteland_3/",
    "GreedFall - Action RPG set in a fantasy world inspired by the 17th century https://store.steampowered.com/app/594650/GreedFall/",
    "Ghost Recon Wildlands - Open-world tactical shooter set in Bolivia https://store.steampowered.com/app/440900/Tom_Clancys_Ghost_Recon_Wildlands/",
    "Far Cry New Dawn - Open-world first-person shooter set in a post-apocalyptic world https://store.steampowered.com/app/960090/Far_Cry_New_Dawn/",
    "Metro Exodus - Story-driven first-person shooter set in a post-apocalyptic Russia https://store.steampowered.com/app/412020/Metro_Exodus/",
    "Doom Eternal - Fast-paced first-person shooter with brutal combat https://store.steampowered.com/app/3577/Doom_Eternal/",
    "Borderlands 3 - Loot shooter with a focus on cooperative gameplay https://store.steampowered.com/app/397540/Borderlands_3/",
    "Monster Hunter: World - Action RPG focused on hunting monsters https://store.steampowered.com/app/582010/Monster_Hunter_World/",
    "Dragon Age: Inquisition - Action RPG set in a high-fantasy world https://store.steampowered.com/app/1222690/Dragon_Age_Inquisition/",
    "Assassin's Creed IV: Black Flag - Action-adventure game featuring pirates https://store.steampowered.com/app/2400/Assassins_Creed_IV_Black_Flag/",
    "Horizon Zero Dawn - Action RPG with a rich narrative and stunning graphics https://store.steampowered.com/app/1151640/Horizon_Zero_Dawn_Complete_Edition/",
    "Ghost of Tsushima - Action-adventure game set in feudal Japan https://store.steampowered.com/app/1253410/Ghost_of_Tsushima/",
    "Hades - Rogue-like dungeon crawler with engaging storytelling https://store.steampowered.com/app/1145360/Hades/",
    "The Last of Us Part II - Action-adventure game with a focus on narrative and character development https://store.steampowered.com/app/1229410/The_Last_of_Us_Part_II/",
    "FIFA 21 - Soccer simulation game https://store.steampowered.com/app/1517290/FIFA_21/",
    "NBA 2K21 - Basketball simulation game https://store.steampowered.com/app/1371340/NBA_2K21/",
    "Madden NFL 21 - American football simulation game https://store.steampowered.com/app/1492630/Madden_NFL_21/",
    "MLB The Show 21 - Baseball simulation game https://store.steampowered.com/app/622200/MLB_The_Show_21/",
    "WWE 2K Battlegrounds - Arcade wrestling game with over-the-top action https://store.steampowered.com/app/700220/WWE_2K_Battlegrounds/",
    "Guitar Hero III: Legends of Rock - Rhythm game focused on music and guitar gameplay https://store.steampowered.com/app/2200/Guitar_Hero_III_Legends_of_Rock/",
    "Just Dance 2021 - Dance rhythm game that lets you dance to popular songs https://store.steampowered.com/app/1200190/Just_Dance_2021/",
    "Rocksmith 2014 - Music rhythm game that teaches you to play guitar https://store.steampowered.com/app/221680/Rocksmith_2014/",
    "Beat Saber - VR rhythm game where you slice blocks to music https://store.steampowered.com/app/620980/Beat_Saber/",
    "Superhot - Time-bending FPS that makes you think strategically https://store.steampowered.com/app/322500/SUPERHOT/",
    "Pummel Party - Multiplayer party game with mini-games and mayhem https://store.steampowered.com/app/578320/Pummel_Party/",
    "Gang Beasts - Multiplayer brawler with gelatinous characters https://store.steampowered.com/app/285900/Gang_Beasts/",
    "Human: Fall Flat - Physics-based puzzle platformer https://store.steampowered.com/app/477160/Human_Fall_Flat/",
    "Overcooked! 2 - Co-op cooking simulation game https://store.steampowered.com/app/728880/Overcooked_2/",
    "A Way Out - Co-op adventure game that requires two players https://store.steampowered.com/app/122270/A_Way_Out/",
    "It Takes Two - Co-op adventure game with a focus on teamwork https://store.steampowered.com/app/813580/It_Takes_Two/",
    "Keep Talking and Nobody Explodes - Cooperative game where one player defuses a bomb with the help of a manual https://store.steampowered.com/app/341800/Keep_Talking_and_Nobody_Explodes/",
    "Fall Guys: Ultimate Knockout - Multiplayer party game with obstacle courses https://store.steampowered.com/app/1097150/Fall_Guys_Ultimate_Knockout/",
    "Jackbox Party Pack 7 - Collection of party games played on your TV and smartphones https://store.steampowered.com/app/1250220/The_Jackbox_Party_Pack_7/",
    "Among Us - Social deduction game where players work together to find the imposter https://store.steampowered.com/app/945360/Among_Us/",
    "Satisfactory - Factory building and automation game in a first-person perspective https://store.steampowered.com/app/526870/Satisfactory/",
    "Raft - Survival game set on the ocean where you gather resources to survive https://store.steampowered.com/app/648450/Raft/",
    "Valheim - Survival and exploration game set in a Norse mythology-inspired world https://store.steampowered.com/app/892970/Valheim/",
    "Phasmophobia - Asymmetrical horror multiplayer game focused on ghost hunting https://store.steampowered.com/app/739630/Phasmophobia/",
    "Deep Rock Galactic - Co-op first-person shooter where you play as dwarves mining on alien planets https://store.steampowered.com/app/548430/Deep_Rock_Galactic/",
    "Noita - Action roguelike where every pixel is simulated https://store.steampowered.com/app/881100/Noita/",
    "The Binding of Isaac: Rebirth - Roguelike dungeon crawler with dark themes and humor https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/",
    "The Last of Us Part II - Action-adventure game with a focus on narrative and character development https://store.steampowered.com/app/1229410/The_Last_of_Us_Part_II/",
    "FIFA 21 - Soccer simulation game https://store.steampowered.com/app/1517290/FIFA_21/",
    "NBA 2K21 - Basketball simulation game https://store.steampowered.com/app/1371340/NBA_2K21/",
    "Madden NFL 21 - American football simulation game https://store.steampowered.com/app/1492630/Madden_NFL_21/",
    "MLB The Show 21 - Baseball simulation game https://store.steampowered.com/app/622200/MLB_The_Show_21/",
    "WWE 2K Battlegrounds - Arcade wrestling game with over-the-top action https://store.steampowered.com/app/700220/WWE_2K_Battlegrounds/",
    "Guitar Hero III: Legends of Rock - Rhythm game focused on music and guitar gameplay https://store.steampowered.com/app/2200/Guitar_Hero_III_Legends_of_Rock/",
    "Just Dance 2021 - Dance rhythm game that lets you dance to popular songs https://store.steampowered.com/app/1200190/Just_Dance_2021/",
    "Rocksmith 2014 - Music rhythm game that teaches you to play guitar https://store.steampowered.com/app/221680/Rocksmith_2014/",
    "Beat Saber - VR rhythm game where you slice blocks to music https://store.steampowered.com/app/620980/Beat_Saber/",
    "Superhot - Time-bending FPS that makes you think strategically https://store.steampowered.com/app/322500/SUPERHOT/",
    "Pummel Party - Multiplayer party game with mini-games and mayhem https://store.steampowered.com/app/578320/Pummel_Party/",
    "Gang Beasts - Multiplayer brawler with gelatinous characters https://store.steampowered.com/app/285900/Gang_Beasts/",
    "Human: Fall Flat - Physics-based puzzle platformer https://store.steampowered.com/app/477160/Human_Fall_Flat/",
    "Overcooked! 2 - Co-op cooking simulation game https://store.steampowered.com/app/728880/Overcooked_2/",
    "A Way Out - Co-op adventure game that requires two players https://store.steampowered.com/app/122270/A_Way_Out/",
    "It Takes Two - Co-op adventure game with a focus on teamwork https://store.steampowered.com/app/813580/It_Takes_Two/",
    "Keep Talking and Nobody Explodes - Cooperative game where one player defuses a bomb with the help of a manual https://store.steampowered.com/app/341800/Keep_Talking_and_Nobody_Explodes/",
    "Fall Guys: Ultimate Knockout - Multiplayer party game with obstacle courses https://store.steampowered.com/app/1097150/Fall_Guys_Ultimate_Knockout/",
    "Jackbox Party Pack 7 - Collection of party games played on your TV and smartphones https://store.steampowered.com/app/1250220/The_Jackbox_Party_Pack_7/",
    "Raft - Survival game set on the ocean where you gather resources to survive https://store.steampowered.com/app/648450/Raft/",
    "Valheim - Survival and exploration game set in a Norse mythology-inspired world https://store.steampowered.com/app/892970/Valheim/",
    "Phasmophobia - Asymmetrical horror multiplayer game focused on ghost hunting https://store.steampowered.com/app/739630/Phasmophobia/",
    "Deep Rock Galactic - Co-op first-person shooter where you play as dwarves mining on alien planets https://store.steampowered.com/app/548430/Deep_Rock_Galactic/",
    "Noita - Action roguelike where every pixel is simulated https://store.steampowered.com/app/881100/Noita/",
    "The Last of Us Part II - Action-adventure game with a focus on narrative and character development https://store.steampowered.com/app/1229410/The_Last_of_Us_Part_II/",
    "The Witcher 3: Wild Hunt - Action RPG set in a rich fantasy world https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
    "Cyberpunk 2077 - Open-world RPG set in a dystopian future https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
    "Genshin Impact - Action RPG set in an open world with gacha mechanics https://store.steampowered.com/app/1819550/Genshin_Impact/",
    "Tales of Arise - Action RPG set in a fantasy world https://store.steampowered.com/app/1001920/Tales_of_Arise/",
    "Disco Elysium - Narrative-driven RPG with unique mechanics https://store.steampowered.com/app/632470/Disco_Elysium/",
    "Path of Exile - Free-to-play action RPG with deep mechanics https://store.steampowered.com/app/238960/Path_of_Exile/",
    "Hades - Rogue-like dungeon crawler with engaging storytelling https://store.steampowered.com/app/1145360/Hades/",
    "Darkest Dungeon - Turn-based RPG that focuses on the psychological stresses of adventuring https://store.steampowered.com/app/262060/Darkest_Dungeon/",
    "Baldur's Gate 3 - RPG set in the Dungeons & Dragons universe https://store.steampowered.com/app/1086940/Baldurs_Gate_3/",
    "Total War: Three Kingdoms - Strategy game set in ancient China during the Three Kingdoms period https://store.steampowered.com/app/779340/Total_War_Three_Kingdoms/",
    "Warhammer 40,000: Dawn of War III - Real-time strategy game set in the Warhammer 40K universe https://store.steampowered.com/app/285620/Warhammer_40000_Dawn_of_War_III/",
    "Starcraft II - Real-time strategy game set in a sci-fi universe https://store.steampowered.com/app/206280/Starcraft_II/",
    "Company of Heroes 2 - Real-time strategy game set in WWII https://store.steampowered.com/app/231430/Company_of_Heroes_2/",
    "Crusader Kings III - Grand strategy game focusing on dynasty management https://store.steampowered.com/app/1158310/Crusader_Kings_III/",
    "Hearts of Iron IV - WWII strategy game that lets you control a nation during the war https://store.steampowered.com/app/394360/Hearts_of_Iron_IV/",
    "Age of Empires IV - Real-time strategy game set in historical periods https://store.steampowered.com/app/813780/Age_of_Empires_IV/",
    "Civilization VI - Turn-based strategy game where you build an empire and compete against others https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/",
    "XCOM 2 - Turn-based strategy game where you fight against an alien occupation of Earth https://store.steampowered.com/app/268500/XCOM_2/",
    "Wasteland 3 - Post-apocalyptic RPG with strategic combat https://store.steampowered.com/app/719040/Wasteland_3/",
    "Ghost Recon Breakpoint - Tactical shooter set in an open world https://store.steampowered.com/app/752170/Tom_Clancys_Ghost_Recon_Breakpoint/",
    "Far Cry 5 - Open-world first-person shooter set in Montana https://store.steampowered.com/app/552520/Far_Cry_5/",
    "The Outer Worlds - Action RPG set in a retro-futuristic space setting https://store.steampowered.com/app/578650/The_Outer_Worlds/",
    "Dragon Age: Inquisition - Action RPG set in a high-fantasy world https://store.steampowered.com/app/1222690/Dragon_Age_Inquisition/",
    "Monster Hunter: World - Action RPG focused on hunting monsters https://store.steampowered.com/app/582010/Monster_Hunter_World/",
    "Doom Eternal - Fast-paced first-person shooter with brutal combat https://store.steampowered.com/app/3577/Doom_Eternal/",
    "Borderlands 3 - Loot shooter with a focus on cooperative gameplay https://store.steampowered.com/app/397540/Borderlands_3/",
    "Ghost of Tsushima - Action-adventure game set in feudal Japan https://store.steampowered.com/app/1253410/Ghost_of_Tsushima/",
    "Hades - Rogue-like dungeon crawler with engaging storytelling https://store.steampowered.com/app/1145360/Hades/",
    "The Witcher 3: Wild Hunt - Action RPG set in a rich fantasy world https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
    "Cyberpunk 2077 - Open-world RPG set in a dystopian future https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
    "Path of Exile - Free-to-play action RPG with deep mechanics https://store.steampowered.com/app/238960/Path_of_Exile/",
    "Disco Elysium - Narrative-driven RPG with unique mechanics https://store.steampowered.com/app/632470/Disco_Elysium/",
    "Baldur's Gate 3 - RPG set in the Dungeons & Dragons universe https://store.steampowered.com/app/1086940/Baldurs_Gate_3/",
    "Valheim - Survival and exploration game set in a Norse mythology-inspired world https://store.steampowered.com/app/892970/Valheim/",
    "Phasmophobia - Asymmetrical horror multiplayer game focused on ghost hunting https://store.steampowered.com/app/739630/Phasmophobia/",
    "Deep Rock Galactic - Co-op first-person shooter where you play as dwarves mining on alien planets https://store.steampowered.com/app/548430/Deep_Rock_Galactic/",
    "Raft - Survival game set on the ocean where you gather resources to survive https://store.steampowered.com/app/648450/Raft/",
    "Grounded - Survival game that shrinks players to the size of insects https://store.steampowered.com/app/753240/Grounded/",
    "Satisfactory - Factory building and automation game in a first-person perspective https://store.steampowered.com/app/526870/Satisfactory/",
    "Pummel Party - Multiplayer party game with mini-games and mayhem https://store.steampowered.com/app/578320/Pummel_Party/",
    "Gang Beasts - Multiplayer brawler with gelatinous characters https://store.steampowered.com/app/285900/Gang_Beasts/",
    "Human: Fall Flat - Physics-based puzzle platformer https://store.steampowered.com/app/477160/Human_Fall_Flat/",
    "Overcooked! 2 - Co-op cooking simulation game https://store.steampowered.com/app/728880/Overcooked_2/",
    "A Way Out - Co-op adventure game that requires two players https://store.steampowered.com/app/122270/A_Way_Out/",
    "It Takes Two - Co-op adventure game with a focus on teamwork https://store.steampowered.com/app/813580/It_Takes_Two/",
    "Keep Talking and Nobody Explodes - Cooperative game where one player defuses a bomb with the help of a manual https://store.steampowered.com/app/341800/Keep_Talking_and_Nobody_Explodes/",
    "Fall Guys: Ultimate Knockout - Multiplayer party game with obstacle courses https://store.steampowered.com/app/1097150/Fall_Guys_Ultimate_Knockout/",
    "Jackbox Party Pack 7 - Collection of party games played on your TV and smartphones https://store.steampowered.com/app/1250220/The_Jackbox_Party_Pack_7/",
    "Among Us - Social deduction game where players work together to find the imposter https://store.steampowered.com/app/945360/Among_Us/",
    "Phasmophobia - Asymmetrical horror multiplayer game focused on ghost hunting https://store.steampowered.com/app/739630/Phasmophobia/",
    "Grounded - Survival game that shrinks players to the size of insects https://store.steampowered.com/app/753240/Grounded/",
    "Noita - Action roguelike where every pixel is simulated https://store.steampowered.com/app/881100/Noita/",
    "The Binding of Isaac: Rebirth - Roguelike dungeon crawler with dark themes and humor https://store.steampowered.com/app/250900/The_Binding_of_Isaac_Rebirth/"
]

browser_game_ideas = [
    "Slither.io - Multiplayer snake game https://slither.io/",
    "Agar.io - Cell-eating multiplayer game https://agar.io/",
    "Krunker.io - Fast-paced FPS https://krunker.io/",
    "Realm of the Mad God - Bullet-hell MMO https://www.realmofthemadgod.com/",
    "GeoGuessr - Geography guessing game https://www.geoguessr.com/",
    "Pokemon Showdown - Online Pokémon battle simulator https://pokemonshowdown.com/",
    "Little Alchemy 2 - Element mixing puzzle game https://littlealchemy2.com/",
    "Shell Shockers - Multiplayer egg shooter https://shellshock.io/",
    "Zombs Royale - 2D battle royale https://zombsroyale.io/",
    "Diep.io - Tank arena game https://diep.io/",
    "Paper.io - Territory capturing game https://paper-io.com/",
    "Cookie Clicker - Classic idle game https://orteil.dashnet.org/cookieclicker/",
    "Town of Salem - Social deduction game https://www.blankmediagames.com/TownOfSalem/",
    "Hole.io - Absorb and grow game https://hole-io.com/",
    "Skribbl.io - Online drawing and guessing https://skribbl.io/",
    "Tanki Online - Multiplayer tank combat https://tankionline.com/",
    "War Brokers - FPS battle royale https://warbrokers.io/",
    "Forge of Empires - City-building strategy game https://www.forgeofempires.com/",
    "World’s Biggest Pac-Man - Massive online Pac-Man https://worldsbiggestpacman.com/",
    "Flight - Casual flying and upgrade game https://www.kongregate.com/games/armorgames/flight",
    "Line Rider - Creative physics game https://www.linerider.com/",
    "Bloons Tower Defense 5 - Tower defense game https://ninjakiwi.com/Games/Bloons-Tower-Defense-5.html",
    "AdventureQuest Worlds - Online RPG https://www.aq.com/",
    "Realm Grinder - Fantasy idle game https://store.steampowered.com/app/610080/Realm_Grinder/",
    "DarkOrbit Reloaded - Space shooter MMO https://www.darkorbit.com/",
    "Surviv.io - 2D battle royale https://surviv.io/",
    "Mope.io - Animal evolution game https://mope.io/",
    "Starve.io - Survival game with crafting http://starve.io/",
    "Narwhale.io - Battle game with narwhals https://narwhale.io/",
    "Lordz.io - Strategy and conquest game http://lordz.io/",
    "Crossy Road - Endless arcade hopper https://crossyroad.com/",
    "Worms Zone - Snake-like multiplayer game https://wormszone.com/",
    "Clicker Heroes - Idle RPG with leveling https://www.clickerheroes.com/",
    "Nitro Type - Typing and racing game https://www.nitrotype.com/",
    "Shell Shockers - Egg-based FPS with online multiplayer https://shellshock.io/",
    "WormsZone.io - Battle Royale style game where you control worms https://wormszone.com/",
    "Superhex.io - Hexagon territory capture game https://superhex.io/",
    "Moomoo.io - Gather resources and build a base to survive https://moomoo.io/",
    "Fidget Spinner Game - Click and collect points with fidget spinners https://fidgetspinnergame.com/",
    "Brawlhalla - Free-to-play platform fighting game https://www.brawlhalla.com/",
    "Falling Sand Game - Sandbox game with falling sand and physics https://fallsand.com/",
    "Super Mario Bros. - Play the classic platformer online https://www.smbgame.com/",
    "Roblox - Online platform to create and play games made by users https://www.roblox.com/",
    "Gartic Phone - Drawing and guessing game similar to Telephone https://garticphone.com/",
    "Zombs.io - Build and defend against zombies in this multiplayer game https://zombs.io/",
    "Splix.io - Take over territory by creating a line in this competitive game https://splix.io/",
    "Agar.io - Eat smaller cells and avoid being eaten in this multiplayer game https://agar.io/",
    "Counter-Strike 1.6 - Browser version of the iconic FPS game https://cs-online.club/",
    "Bubble Shooter - Classic bubble shooting game https://www.bubbleshooter.com/",
    "2048 - Join numbers to reach 2048 in this addictive puzzle game https://2048game.com/",
    "Lands of Lore - Classic RPG online browser version https://landsoflore.com/",
    "Sonic Dash - Endless runner game featuring Sonic the Hedgehog https://sonicdash.com/",
    "Tetris - Classic Tetris game online https://tetrischampion.com/",
    "AdventureQuest - Classic RPG with quests and battles https://www.battleon.com/",
    "Slime Rancher - Manage and cultivate a ranch of slimes in this browser game https://slimerancher.com/",
    "Madalin Stunt Cars 2 - Racing game with stunts in an open world https://madalinstuntcars.com/",
    "Super Mario 63 - Fan-made Mario game in a 3D environment https://supermario63.com/",
    "Idle Breakout - Incremental game based on breaking bricks https://idlebreakout.com/",
    "Barbie Games - Play a variety of Barbie-themed games https://www.barbie.com/en-us/games/",
    "Piano Tiles - Tap the black tiles as they fall in this rhythm game https://pianotiles.org/",
    "Drift Hunters - Online drifting game with customizable cars https://drifthunters.com/",
    "Bomb It - Classic multiplayer bomberman-style game https://bombit.net/",
    "Minecraft Classic - Play the original version of Minecraft in your browser https://classic.minecraft.net/",
    "Totally Accurate Battle Simulator - Simulation game with wacky physics https://tabsgame.com/",
    "Fleeing the Complex - Interactive stickman adventure game https://puffballs.com/games/fleeing-the-complex/",
    "Google Doodle Games - Fun mini-games featured in Google Doodles https://www.google.com/doodles/",
    "World of Warships - Naval combat game set in World War II https://worldofwarships.com/",
    "Hero Wars - Fantasy RPG with heroes and battles https://hero-wars.com/",
    "Poptropica - Adventure game with quests and puzzles https://www.poptropica.com/",
    "Blooket - Educational game with trivia and challenges https://www.blooket.com/",
    "Genshin Impact - Action RPG with a vast open world https://genshin.hoyoverse.com/",
    "Kongregate - Platform with a variety of browser games https://www.kongregate.com/",
    "Fall Guys - Browser-based version of the popular battle royale game https://www.fallguys.com/",
    "Super Smash Flash - Fan-made version of Super Smash Bros https://supersmashflash.com/",
    "Nitrome Games - Collection of pixel art games from Nitrome https://www.nitrome.com/",
    "Duck Life - Fun game where you train a duck to race https://www.ducklife.com/",
    "Bubble Shooter 2 - Second installment of the popular bubble shooter game https://www.bubbleshooter2.com/",
    "Gold Miner - Classic mining game where you collect gold and gems https://goldminer.com/",
    "Frogger - Play the classic arcade game online https://frogger.com/",
    "Spank the Monkey - Click game to spank the monkey and earn points https://spankthemonkey.com/",
    "Chuzzle - Match the colorful chuzzles in this puzzle game https://chuzzle.com/",
    "Zomboz - Multiplayer shooting game where you kill zombies https://zomboz.com/",
    "Flappy Bird - Play the classic Flappy Bird game online https://flappybird.io/",
    "Minecraft: Story Mode - Interactive story game set in the Minecraft universe https://www.telltalegames.com/games/minecraft-story-mode/",
    "Sonic 3D - Play Sonic in 3D online https://sonic3d.com/",
    "Agar.io - Multiplayer battle game with cells https://agar.io/",
    "Little Big Snake - Evolving snake game similar to Slither.io https://littlebigsnake.com/",
    "Bomberman - Classic multiplayer bomberman-style game https://bomberman.com/",
    "Cartoon Network Games - A collection of games based on Cartoon Network characters https://www.cartoonnetwork.com/games/",
    "Sonic Dash 2 - Endless runner featuring Sonic and friends https://sonicdash2.com/",
    "Cookie Clicker 2 - An incremental game with more features https://orteil.dashnet.org/cookieclicker2/",
    "Warriors.io - Fight against players in a multiplayer arena https://warriors.io/",
    "Wormax.io - Multiplayer worm game with a twist https://wormax.io/",
    "Swoop - Control a bird to swoop and gather food https://swoop.com/",
    "Hero Factory - Build and battle heroes in this creative game https://herofactory.com/",
    "Fidget Spinner - A virtual fidget spinner game https://fidgetspinner.com/",
    "Tricky Test - Brain teaser game with tricky questions https://trickytest.com/",
    "Rogue Soul - Run and jump through levels in this platformer https://roguesoul.com/",
    "Crush the Castle - Physics-based destruction game https://crushthecastle.com/",
    "Super Mario Flash - Flash-based Mario game with levels to complete https://supermarioflash.com/",
    "Unturned - Zombie survival game available in browser https://unturned.io/",
    "Penguin Diner - Help a penguin serve customers in this diner game https://penguindiner.com/",
    "Pet Rescue Saga - Match and save pets in this puzzle game https://petrescuesaga.com/",
    "Granny - Horror game where you escape a creepy house https://grannygame.com/",
    "Huggy Wuggy - Survive against Huggy Wuggy in this horror game https://huggywuggygame.com/",
    "Imposter - Multiplayer deduction game inspired by Among Us https://impostergame.com/",
    "Flappy Golf - Golf and Flappy Bird combined into one game https://flappygolf.com/",
    "Falling Sand Game - Sandbox physics game where you control falling sand https://fallsand.com/",
    "Sushi Cat - Help a cat eat sushi in this fun puzzle game https://sushicat.com/",
    "Slither.io - Battle against others in this multiplayer snake game https://slither.io/",
    "Roblox - Online platform to create and play games made by users https://www.roblox.com/",
    "Pogo Games - Collection of casual games to play online https://www.pogo.com/",
    "Quake JS - Play Quake in your browser with this version https://quakejs.com/",
    "DuckDuckGo Games - Fun mini-games to play through DuckDuckGo https://duckduckgo.com/games/",
    "Bloxorz - Solve puzzles by moving the block to the exit https://bloxorz.com/",
    "Rider - Motorcycle racing game with tricks https://rider.com/",
    "Agar.io - Eat cells and grow in this multiplayer game https://agar.io/",
    "Kingdom Rush - Popular tower defense game with heroes https://www.kingdomrush.com/",
    "Stick War - Strategy game where you control an army of stick figures https://stickwar.com/",
    "Pixel Warfare - FPS with pixel graphics and online multiplayer https://pixelwarfare.com/",
    "Panda Rescue - Help pandas solve puzzles and escape https://pandarecue.com/",
    "Bloons TD - Tower defense game with bloons https://bloonstd.com/",
    "Gummy Drop - Match-3 game with gummy candies https://gummydrop.com/",
    "Shell Shockers - First-person shooter where you play as an egg https://shellshockers.io/",
    "Battlegrounds - Battle royale game with multiplayer elements https://battlegrounds.io/",
    "Rocket League - Play Rocket League in the browser https://rocketleague.com/",
    "Snake.is - Another take on the classic snake game https://snake.is/",
    "WormsZone.io - Snake-style multiplayer game https://wormszone.io/",
    "Burrito Bison - RPG where you launch a burrito bison to fight enemies https://burritobison.com/",
    "Paper.io 2 - New version of the territory capturing game https://paperio2.com/",
    "Drift Hunters - Racing game with drift mechanics https://drifthunters.com/",
    "Sonic the Hedgehog - Play classic Sonic the Hedgehog in browser https://sonic.com/",
    "Super Mario 63 - Play a flash version of Super Mario 63 online https://supermario63.com/",
    "Sonic Mania - Play Sonic Mania in your browser https://sonicmania.com/",
    "Fruit Ninja - Slice fruit and avoid bombs in this arcade game https://fruitninja.com/",
    "Wormax.io - Control a worm and grow larger in multiplayer https://wormax.io/",
    "Tetris - Classic puzzle game available in your browser https://tetris.com/",
    "Tank Trouble - Multiplayer tank battle game https://tanktrouble.com/",
    "Super Stickman Golf - Golf game with stickman characters https://stickmangolf.com/",
    "Sky Arena - Battle other players in an aerial arena https://skyarena.com/",
    "Magic Piano - Play the piano in this rhythm game https://magicpiano.com/",
    "Piano Tiles 2 - Tap the black tiles in this musical game https://pianotiles2.com/",
    "Angry Birds - Play the classic Angry Birds game in your browser https://angrybirds.com/",
    "Duck Life 3 - Train your duck to compete in races https://ducklife.com/",
    "Street Fighter II - Play the classic Street Fighter II online https://streetfighter.com/",
    "Transformice - Multiplayer platform game with mice https://transformice.com/",
    "Fighting Games - Collection of various fighting games https://fightinggames.com/",
    "Mario Kart - Play the classic racing game online https://mariokart.com/",
    "The Binding of Isaac - Indie roguelike game available in browser https://bindingofisaac.com/",
    "Sonic Dash - Endless runner featuring Sonic the Hedgehog https://sonicdash.com/",
    "Geometry Dash - Rhythm-based platforming game https://geometrydash.com/",
    "Battle for the Galaxy - Strategy game where you build and battle https://battleforthegalaxy.com/",
    "Galactic Civilizations - Space strategy game in your browser https://galacticcivilizations.com/",
    "Happy Wheels - Physics-based ragdoll game https://happywheels.com/",
    "Hockey Legends - Online hockey game with various modes https://hockeylegends.com/",
    "World's Biggest Pac-Man - Massive version of the classic game https://worldsbiggestpacman.com/",
    "Swords and Souls - RPG where you train a warrior https://swordsandsouls.com/",
    "Pikachu Games - Collection of Pikachu-themed games https://pikachugames.com/",
    "Drift City - Racing game with drift mechanics and car customization https://driftcity.com/",
    "Tiny Fishing - Catch fish and upgrade your gear https://tinyfishing.com/",
    "Baby Hazel - Help Baby Hazel in various adventures https://babyhazel.com/",
    "Granny - Horror game where you escape a creepy house https://grannygame.com/",
    "Doodle Jump - Jump your way up the platforms in this classic game https://doodlejump.com/",
    "Scrabble - Play Scrabble online against friends https://scrabble.com/",
    "Mahjongg - Play the classic Mahjong game online https://mahjongg.com/",
    "Chess - Play chess against friends or the computer https://chess.com/",
    "Battleship - Classic naval strategy game online https://battleship.com/",
    "Mario Kart - Play Mario Kart in your browser https://mariokart.com/",
    "Five Nights at Freddy's - Survive the night in this horror game https://fivenightsatfreddys.com/",
    "Madalin Stunt Cars 2 - Racing game with stunts in an open world https://madalinstuntcars.com/",
    "Death Run 3D - Fast-paced parkour game with traps https://deathrun3d.com/",
    "Stickman Hook - Swing through levels as a stickman https://stickmanhook.com/",
    "Flip Master - Perform tricks on a trampoline in this game https://flipmaster.com/",
    "Super Slope - Navigate a ball down a slope in this racing game https://superslope.com/",
    "Sky Streaker - Jump from building to building in this platformer https://skystreaker.com/",
    "Pac-Man 256 - Endless maze game with power-ups https://pacman256.com/",
    "Codenames - Online version of the popular party game https://codenames.game/",
    "Pogo Games - A variety of casual games to play online https://www.pogo.com/",
    "Chess.com - Play chess online against players worldwide https://chess.com/",
    "Skribbl.io - Online drawing and guessing game https://skribbl.io/",
    "Tank Trouble - Battle tanks in this multiplayer game https://tanktrouble.com/",
    "Dino Run - Run and avoid obstacles in this endless runner https://dinorun.com/",
    "Helix Jump - Navigate a ball through a helix tower https://helixjump.com/",
    "Google Chrome Dino - Play the offline dinosaur game in your browser https://chrome.google.com/webstore/detail/dino-game/",
    "Doodle God - Mix elements to create new ones in this puzzle game https://doodlegod.com/",
    "Color Switch - Tap to jump and avoid obstacles in this arcade game https://colorswitch.com/",
    "Candy Crush - Match candies in this addictive puzzle game https://candycrush.com/",
    "Bloons TD 6 - Tower defense game with bloons https://bloonstd.com/",
    "Table Tennis - Play table tennis against the computer or a friend https://tabletennis.com/",
    "Reversi - Classic board game online https://reversi.com/",
    "2048 - Join numbers to reach 2048 in this addictive puzzle game https://2048game.com/",
    "Color Fill - Fill the grid with colors in this puzzle game https://colorfill.com/",
    "Bubble Shooter - Classic bubble shooter game https://bubbleshooter.com/",
    "Parcheesi - Online version of the classic board game https://parcheesi.com/",
    "Crazy Taxi - Drive a taxi and pick up customers in this game https://crazytaxi.com/",
    "Flappy Bird - Fly through obstacles with your bird in this challenging game https://flappybird.io/",
    "World's Biggest Pac-Man - Explore a huge version of the classic arcade game https://worldsbiggestpacman.com/",
    "Sumo Paint - Create art and paint online with Sumo Paint https://sumopaint.com/",
    "Gartic Phone - Drawing and guessing game where players take turns https://garticphone.com/",
    "Duck Life 4 - Train your duck and compete in races https://ducklife.com/",
    "Bad Ice Cream - Cooperative ice cream game where you avoid enemies https://badicecream.com/",
    "Demon's Souls - Action RPG available to play online https://demonssouls.com/",
    "Burnout Drift - Drift racing game with customizable cars https://burnoutdrift.com/",
    "Mr. Bullet - Solve puzzles by shooting enemies in this game https://mrbullet.com/",
    "Papa's Pizzeria - Run your own pizzeria in this cooking game https://papaspizzeria.com/",
    "Sushi Cat 2 - Help Sushi Cat eat sushi and grow in this puzzle game https://sushicat2.com/",
    "Funfair Ride Simulator - Control a virtual amusement park ride https://funfairride.com/",
    "Block Puzzle - Classic block puzzle game with different levels https://blockpuzzle.com/",
    "Makeover Games - Dress up and makeover games to play online https://makeovergames.com/",
    "Bunny Hop - Jump from platform to platform in this cute game https://bunnyhop.com/",
    "Aquarium Coaster - Create and manage your own aquarium park https://aquariumcoaster.com/",
    "Kingdom Rush Frontiers - Tower defense game with heroes and upgrades https://kingdomrush.com/",
    "Pirate101 - MMORPG where you play as a pirate https://pirate101.com/",
    "Warframe - Action RPG with cooperative gameplay available in browser https://warframe.com/",
    "Bleach Online - MMORPG based on the Bleach anime series https://bleachonline.com/",
    "Angry Birds 2 - Second installment of the popular game https://angrybirds.com/",
    "Clash of Clans - Build and battle in this strategy game https://clashofclans.com/",
    "Portal - Play the classic puzzle game in your browser https://portal.com/",
    "World of Tanks - Tank battle game with online multiplayer https://worldoftanks.com/",
    "Call of Duty - Play Call of Duty in your browser https://callofduty.com/",
    "Farm Heroes Saga - Match and collect crops in this puzzle game https://farmheroessaga.com/",
    "Ben 10 Games - Play various Ben 10-themed games online https://ben10.com/games/",
    "Minecraft Classic - Play the original Minecraft game in your browser https://classic.minecraft.net/",
    "Geometry Dash Lite - Play the free version of Geometry Dash online https://geometrydashlite.com/",
    "The Sims - Online version of the classic life simulation game https://thesims.com/",
    "Stardew Valley - Farming simulation game available in browser https://stardewvalley.com/",
    "Crossy Road - Help characters cross roads and rivers in this endless game https://crossyroad.com/",
    "Mario Kart - Play the classic racing game online https://mariokart.com/",
    "Minecraft Dungeons - Dungeon crawler based on the Minecraft universe https://minecraftdungeons.com/",
    "Gang Beasts - Multiplayer brawler game with funny physics https://gangbeasts.com/",
    "Mario Sports - Play sports games featuring Mario and friends https://mariosports.com/",
    "Sonic Generations - Play classic and modern Sonic levels https://sonicgenerations.com/",
    "Unfair Mario - Platformer where the levels are unfairly designed https://unfairmario.com/",
    "Candy Crush Saga - Match candies in this addictive game https://candycrush.com/",
    "Epic Battle Fantasy - RPG with turn-based battles and humor https://epicbattlefantasy.com/",
    "Agar.io - Eat cells and grow in this multiplayer game https://agar.io/",
    "Fireboy and Watergirl - Cooperative puzzle platformer game https://fireboyandwatergirl.com/",
    "Zodiac Games - Play games related to zodiac signs https://zodiacgames.com/",
    "Farm Together - Build and manage your farm in this simulation game https://farmtogether.com/",
    "Horizon Chase - Racing game with retro graphics https://horizonchase.com/",
    "Demon's Souls - Action RPG available to play online https://demonssouls.com/",
    "Monster Legends - Strategy game with monsters and battles https://monsterlegends.com/",
    "Cut the Rope - Puzzle game where you cut ropes to feed a monster https://cuttherope.com/",
    "Google Chrome Dino - Play the offline dinosaur game in your browser https://chrome.google.com/webstore/detail/dino-game/",
    "Sword Fight - Battle against other players in this sword fighting game https://swordfight.com/",
    "Murder Mystery - Solve the mystery in this online game https://murdermystery.com/",
    "Cooking Fever - Cooking simulation game with various recipes https://cookingfever.com/",
    "Beach Buggy Racing - Race on the beach in this fun game https://beachbuggyracing.com/",
    "Gravity Falls - Explore the Gravity Falls universe in this adventure game https://gravityfalls.com/",
    "Cooking Games - Play various cooking-themed games online https://cookinggames.com/",
    "Pac-Man - Play the classic arcade game online https://pacman.com/",
    "Duck Hunt - Play the classic hunting game in your browser https://duckhunt.com/",
    "Car Parking - Park your car in various challenging scenarios https://carparking.com/",
    "Baseball Games - Collection of baseball-themed games to play online https://baseballgames.com/",
    "Ultimate Tic Tac Toe - Play the advanced version of Tic Tac Toe online https://ultimatetictactoe.com/",
    "Super Mario Bros. - Play the classic platformer online https://www.smbgame.com/",
    "Escape Room Games - Solve puzzles to escape the room in this series https://escaperoomgames.com/",
    "Happy Wheels - Play the popular ragdoll game in your browser https://happywheels.com/",
    "Warframe - Action RPG with cooperative gameplay available in browser https://warframe.com/",
    "House of the Dead - Survive against zombies in this classic arcade game https://houseofthedead.com/",
    "Slither.io - Multiplayer snake game https://slither.io/",
    "Mario Kart - Play the classic racing game online https://mariokart.com/",
    "Super Smash Bros - Play the classic fighting game with characters https://supersmashbros.com/",
    "Fruity Slots - Play a fruit-themed slots game online https://fruityslots.com/",
    "Brawlhalla - Free-to-play platform fighting game https://www.brawlhalla.com/",
    "Pictionary - Online drawing and guessing game https://pictionary.com/",
    "Stick Fight - Fight against other players in this stickman brawler https://stickfight.com/",
    "Minecraft Dungeons - Dungeon crawler based on the Minecraft universe https://minecraftdungeons.com/",
    "Sudoku - Play the classic number puzzle game online https://sudoku.com/",
    "Bowling Games - Collection of bowling-themed games to play online https://bowlinggames.com/",
    "The Escapists - Strategy game where you escape from prison https://theescapists.com/",
    "Piano Games - Play piano-themed games online https://pianogames.com/",
    "Kingdom Rush - Tower defense game with heroes and upgrades https://kingdomrush.com/",
    "The Last Stand - Survive against waves of zombies in this shooter game https://thelaststand.com/",
    "Horizon Chase - Retro racing game with vibrant graphics https://horizonchase.com/",
    "Plague Inc - Strategy simulation game where you create a virus https://plagueinc.com/",
    "Bubble Trouble - Pop bubbles before they touch the ground https://bubbletrouble.com/",
    "Dream Car Racing - Design and race your own car in this game https://dreamcarracing.com/",
    "Line Rider - Create and ride your own lines in this physics game https://www.linerider.com/",
    "Battle Blocks - Multiplayer battle game with blocks https://battleblocks.com/",
    "Speed Racing - Fast-paced racing game with customizable cars https://speedracing.com/",
    "Bricks Breaker - Break bricks with a ball in this classic game https://bricksbreaker.com/",
    "Monsters, Inc. - Play games based on the Monsters, Inc. franchise https://monstersinc.com/",
    "Run 3 - Endless runner in a 3D environment https://run3.com/",
    "Fireboy and Watergirl - Help the duo solve puzzles in this platform game https://fireboyandwatergirl.com/",
    "Zombocalypse - Survive against waves of zombies in this action game https://zombocalypse.com/",
    "Bubble Spinner - Spin and pop bubbles in this fun game https://bubblespinner.com/",
    "Catan Universe - Play the popular board game online https://catanuniverse.com/",
    "Zombotron - Action-packed platformer game with zombies https://zombotron.com/",
    "Drive Mad - Driving game with challenging courses https://drivemad.com/",
    "Tomb Raider - Play as Lara Croft in this classic action game https://tombraider.com/",
    "Gold Miner - Classic arcade mining game where you collect gold https://goldminer.com/",
    "Puzzles - Solve a variety of puzzles online https://puzzles.com/",
    "Rogue Soul 2 - Platformer with fast-paced action https://roguesoul2.com/",
    "Super Mario 63 - Flash version of Super Mario 63 online https://supermario63.com/",
    "Super Meat Boy - Tough platformer game with levels to complete https://supermeatboy.com/",
    "Little Alchemy - Combine elements to create new ones in this puzzle game https://littlealchemy.com/",
    "Mini Golf - Play mini golf in this fun online game https://minigolf.com/",
    "Sonic the Hedgehog - Play classic Sonic the Hedgehog in browser https://sonic.com/",
    "The Binding of Isaac - Indie roguelike game available in browser https://bindingofisaac.com/",
    "Battle Royale - Play battle royale games online https://battleroyale.com/",
    "Zombies - Survive against waves of zombies in this shooter game https://zombies.com/",
    "Bubble Shooter - Classic bubble shooter game online https://bubbleshooter.com/",
    "Sumo Wrestler - Compete in sumo wrestling matches online https://sumowrestler.com/",
    "Duck Hunt - Play the classic hunting game in your browser https://duckhunt.com/",
    "Bejeweled - Match gems in this classic puzzle game https://bejeweled.com/",
    "Super Mario Maker - Create and play levels in this platformer https://supermariomaker.com/",
    "The Room - Solve puzzles in this escape game https://theroom.com/",
    "Jetpack Joyride - Fly and dodge obstacles in this endless runner https://jetpackjoyride.com/",
    "Grand Theft Auto - Play GTA in your browser https://gta.com/",
    "Superhero Games - Play games featuring superheroes online https://superherogames.com/",
    "Cooking Games - Play cooking-themed games online https://cookinggames.com/",
    "Pirate Battle - Sail the seas and battle other pirates online https://piratebattle.com/",
    "Online Solitaire - Play the classic card game online https://solitaire.com/",
    "Warcraft III - Play the classic real-time strategy game online https://warcraft3.com/",
    "Fortnite - Play the popular battle royale game in your browser https://fortnite.com/",
    "Doodle Jump - Jump your way up the platforms in this classic game https://doodlejump.com/",
    "Paper.io - Capture territory in this addictive multiplayer game https://paper.io/",
    "Duck Life - Train and race your duck in this game https://ducklife.com/",
    "Catan Universe - Play the popular board game online https://catanuniverse.com/",
    "Solitaire - Classic solitaire game available to play online https://solitaire.com/",
    "WormsZone.io - Snake-style multiplayer game online https://wormszone.io/",
    "Bubble Shooter - Classic bubble shooter game available online https://bubbleshooter.com/",
    "Online Chess - Play chess online against other players https://chess.com/",
    "Retro Games - Collection of retro games to play online https://retrogames.com/",
    "Banana Games - Fun games featuring bananas to play online https://bananagames.com/",
    "Tower Defense Games - Collection of tower defense games to play online https://towerdefensegames.com/",
    "Maze Games - Solve mazes and puzzles online https://maze.games/",
    "Ninja Games - Play games featuring ninjas online https://ninjagames.com/",
    "Kogama - Play and create 3D multiplayer games https://kogama.com/",
    "Carmen Sandiego - Play games based on the popular franchise https://carmensandiego.com/",
    "Zombies - Survive against waves of zombies in this shooter game https://zombies.com/",
    "Flash Games - Play various flash games online https://flashgames.com/",
    "Squid Games - Play games inspired by Squid Game online https://squidgames.com/",
    "Geometry Dash - Rhythm-based platforming game https://geometrydash.com/",
    "Ragdoll Masters - Battle with ragdoll physics characters https://ragdollmasters.com/",
    "Crossy Road - Help characters cross roads and rivers in this endless game https://crossyroad.com/",
    "Horse Games - Collection of games featuring horses https://horsegames.com/",
    "Roblox - Online platform to create and play games made by users https://www.roblox.com/",
    "Star Wars Games - Play games based on the Star Wars franchise https://starwars.com/games/",
    "Little Alchemy 2 - Create new elements by combining them in this game https://littlealchemy2.com/",
    "Virtual Pet Games - Take care of virtual pets online https://virtualpetgames.com/",
    "Kongregate - Play a variety of online games on this platform https://kongregate.com/",
    "Pixel Art - Create pixel art and designs online https://pixelart.com/",
    "Fishing Games - Play various fishing-themed games online https://fishinggames.com/",
    "Ben 10 Games - Play various Ben 10-themed games online https://ben10.com/games/",
    "Pokemon Games - Play games based on the Pokémon franchise https://pokemon.com/",
    "Star Wars: The Old Republic - MMORPG set in the Star Wars universe https://swtor.com/",
    "PlayStation - Play PlayStation games in your browser https://playstation.com/",
    "Retro Arcade - Play retro arcade games online https://retroarcade.com/",
    "Wormax.io - Multiplayer snake game https://wormax.io/",
    "Math Games - Solve math problems in fun games online https://mathgames.com/",
    "Escape Room Games - Solve puzzles to escape the room in this series https://escaperoomgames.com/",
    "Star Trek Online - Play the MMORPG set in the Star Trek universe https://startrekonline.com/",
    "Trivia Games - Play trivia games online against friends https://triviagames.com/",
    "Tomb Raider - Play as Lara Croft in this classic action game https://tombraider.com/",
    "Jigsaw Puzzles - Solve jigsaw puzzles online https://jigsawpuzzles.com/",
    "Survival Games - Play various survival-themed games online https://survivalgames.com/",
    "Social Deduction Games - Play games that involve social deduction online https://socialdeductiongames.com/",
    "Fireboy and Watergirl - Help the duo solve puzzles in this platform game https://fireboyandwatergirl.com/",
    "Super Mario Flash - Flash-based Mario game with levels to complete https://supermarioflash.com/",
    "DuckLife - Train and race your duck in this game https://ducklife.com/",
    "Match-3 Games - Play various match-3 games online https://match3games.com/",
    "Classic Board Games - Play classic board games online https://classicboardgames.com/",
    "Interactive Fiction - Read and play interactive fiction games online https://interactivefiction.com/",
    "Racing Games - Collection of various racing games online https://racinggames.com/",
    "Educational Games - Play educational-themed games online https://educationalgames.com/",
    "Action Games - Collection of action-themed games online https://actiongames.com/",
    "Word Games - Play various word games online https://wordgames.com/",
    "Shooting Games - Play shooting-themed games online https://shootinggames.com/",
    "Zelda Games - Play games based on the Zelda franchise https://zelda.com/",
    "Horror Games - Collection of horror-themed games to play online https://horrorgames.com/",
    "Maze Games - Solve mazes and puzzles online https://maze.games/",
    "Classic Games - Play classic games online https://classicgames.com/",
    "Virtual Worlds - Explore virtual worlds in games online https://virtualworlds.com/",
    "Arcade Games - Play arcade-style games online https://arcadegames.com/",
    "Endless Runner - Play various endless runner games online https://endlessrunner.com/",
    "Classic RPG - Play classic role-playing games online https://classicsrpg.com/",
    "Cooking Games - Play cooking-themed games online https://cookinggames.com/",
    "Shooting Games - Play shooting-themed games online https://shootinggames.com/",
    "Puzzles - Solve a variety of puzzles online https://puzzles.com/",
    "Interactive Games - Play interactive games online https://interactivegames.com/",
    "Basketball Games - Play basketball-themed games online https://basketballgames.com/",
    "Educational Games - Play educational-themed games online https://educationalgames.com/",
    "Hockey Games - Play hockey-themed games online https://hockeygames.com/",
    "Match-3 Games - Play various match-3 games online https://match3games.com/",
    "Racing Games - Collection of various racing games online https://racinggames.com/",
    "Shooting Games - Play shooting-themed games online https://shootinggames.com/",
    "Poker Games - Play poker games online against friends https://pokergames.com/",
    "Puzzles - Solve a variety of puzzles online https://puzzles.com/",
    "Quizzes - Test your knowledge with online quizzes https://quizzes.com/",
    "Hidden Object Games - Find hidden objects in games online https://hiddenobjectgames.com/",
    "Physics Games - Play games that utilize physics mechanics online https://physicsgames.com/",
    "Superhero Games - Play games featuring superheroes online https://superherogames.com/",
    "Escape Room - Solve puzzles to escape the room in this series https://escaperoom.com/",
    "Dress Up Games - Play dress-up themed games online https://dressupgames.com/",
    "Word Games - Play various word games online https://wordgames.com/",
    "Fun Games - Collection of fun games to play online https://fungames.com/",
    "Farm Games - Play farming-themed games online https://farmgames.com/"
]