# -----------------------------------------------------------------------------------------------------------
# Random Jokes | 1000
funny_jokes = [
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call fake spaghetti? An impasta!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the math book sad? Because it had too many problems.",
    "Why can't you give Elsa a balloon? Because she will let it go!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How do you organize a space party? You planet!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why did the cookie go to the doctor? Because it felt crummy!",
    "What did the zero say to the eight? Nice belt!",
    "Why did the golfer bring an extra pair of socks? In case he got a hole in one!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call an alligator in a vest? An investigator!",
    "Why was the math book sad? It had too many problems.",
    "Why are ghosts bad liars? Because you can see right through them!",
    "What do you call a dog that can do magic? A labracadabrador!",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why don’t skeletons ever use cell phones? They don’t have the guts!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "How does a penguin build its house? Igloos it together!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the belt get arrested? For holding up a pair of pants!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "Why did the frog take the bus to work? His car got toad away!",
    "Why did the man put his money in the blender? Because he wanted to make liquid assets!",
    "What do you call a pile of cats? A meowtain!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why can't your nose be 12 inches long? Because then it would be a foot!",
    "What do you call a bee that can't make up its mind? A maybe!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why did the man run around his bed? Because he was trying to catch up on his sleep!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "What do you call a fish with no eyes? Fsh!",
    "How does a scientist freshen her breath? With experi-mints!",
    "Why did the banana go to the doctor? Because it wasn't peeling well!",
    "What do you get if you cross a cat with a dark horse? Kitty Perry!",
    "Why was the math book sad? Because it had too many problems.",
    "What’s a skeleton’s least favorite room in the house? The living room!",
    "Why did the computer keep freezing? It left its Windows open!",
    "Why did the cow go to outer space? To see the moooon!",
    "Why was the broom late? It swept in!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why don’t oysters donate to charity? Because they are shellfish!",
    "Why did the golfer bring an extra pair of socks? In case he got a hole in one!",
    "Why did the computer go to the doctor? It had a virus!",
    "What do you call a fake noodle? An impasta!",
    "Why did the mushroom go to the party? Because he was a fungi!",
    "What do you call an alligator in a vest? An investigator!",
    "Why don’t eggs tell jokes? Because they’d crack each other up!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the coffee file a police report? It got mugged!",
    "What’s a computer’s favorite snack? Microchips!",
    "Why do cows have hooves instead of feet? Because they lactose!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the belt get arrested? For holding up a pair of pants!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the cookie go to the doctor? Because it felt crummy!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the math book sad? It had too many problems.",
    "Why don’t skeletons fight each other? They don’t have the guts!",
    "What did the zero say to the eight? Nice belt!",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the picture go to jail? Because it was framed!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why was the computer cold? It left its Windows open!",
    "Why did the man put his money in the blender? Because he wanted to make liquid assets!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why was the broom late? It swept in!",
    "How do you organize a space party? You planet!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a fake noodle? An impasta!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How do you organize a space party? You planet!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the cookie go to the doctor? Because it felt crummy!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why can't your nose be 12 inches long? Because then it would be a foot!",
    "What do you call a bee that can't make up its mind? A maybe!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why did the man run around his bed? Because he was trying to catch up on his sleep!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the belt get arrested? For holding up a pair of pants!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "Why did the frog take the bus to work? His car got toad away!",
    "Why did the man put his money in the blender? Because he wanted to make liquid assets!",
    "What do you call a pile of cats? A meowtain!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why can't your nose be 12 inches long? Because then it would be a foot!",
    "What do you call a bee that can't make up its mind? A maybe!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why did the man run around his bed? Because he was trying to catch up on his sleep!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the belt get arrested? For holding up a pair of pants!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "Why did the frog take the bus to work? His car got toad away!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the cookie go to the doctor? Because it felt crummy!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the math book sad? It had too many problems.",
    "Why don’t skeletons fight each other? They don’t have the guts!",
    "What did the zero say to the eight? Nice belt!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
    "What do you call a fake noodle? An impasta!",
    "Why did the coffee file a police report? It got mugged!",
    "What’s a skeleton’s least favorite room in the house? The living room!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call an alligator in a vest? An investigator!",
    "Why don’t eggs tell jokes? Because they’d crack each other up!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why was the broom late? It swept in!",
    "How do you organize a space party? You planet!",
    "What do you call a pile of cats? A meowtain!",
    "What do you call fake spaghetti? An impasta!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the math book sad? Because it had too many problems.",
    "Why don’t skeletons fight each other? They don’t have the guts!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "How does a penguin build its house? Igloos it together!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What’s orange and sounds like a parrot? A carrot!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the computer go to the doctor? It had a virus!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the math book look sad? Because it had too many problems!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "Why do cows have hooves instead of feet? Because they lactose!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "Why did the computer keep freezing? It left its Windows open!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why don’t skeletons ever use cell phones? They don’t have the guts!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How do you organize a space party? You planet!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the cookie go to the doctor? Because it felt crummy!",
    "What’s a skeleton’s least favorite room in the house? The living room!",
    "What do you call fake spaghetti? An impasta!",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the math book sad? Because it had too many problems.",
    "Why don’t skeletons fight each other? They don’t have the guts!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why was the broom late? It swept in!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why did the man run around his bed? Because he was trying to catch up on his sleep!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the math book sad? Because it had too many problems.",
    "Why don’t skeletons fight each other? They don’t have the guts!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "What do you call a fake noodle? An impasta!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the computer go to the doctor? Because it had a virus!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the math book look sad? Because it had too many problems!",
    "Why did the computer keep freezing? It left its Windows open!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the zero say to the eight? Nice belt!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "How do you organize a space party? You planet!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why was the broom late? It swept in!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a fake noodle? An impasta!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a pile of cats? A meowtain!",
    "What did the coffee file a police report? It got mugged!",
    "Why was the math book sad? Because it had too many problems.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the computer go to the doctor? It had a virus!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "What do you call a fake noodle? An impasta!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the computer keep freezing? It left its Windows open!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the chicken go to the seance? To talk to the other side!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the computer go to the doctor? It had a virus!",
    "What do you call an alligator in a vest? An investigator!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a pile of cats? A meowtain!",
    "Why did the man put his money in the blender? Because he wanted to make liquid assets!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the computer keep freezing? It left its Windows open!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why was the math book sad? Because it had too many problems.",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the farmer win an award? Because he was outstanding in his field!",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
    "What do you call a fake noodle? An impasta!",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the cookie go to the doctor? Because it felt crummy!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why was the broom late? It swept in!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the computer go to the doctor? It had a virus!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the stadium get hot after the game? All of the fans left!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the computer keep freezing? It left its Windows open!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the computer go to the doctor? It had a virus!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you call a pile of cats? A meowtain!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the cookie cry? Because its mom was a wafer (away for) so long!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the computer go to the doctor? It had a virus!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you call an alligator in a vest? An investigator!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a fake noodle? An impasta!",
    "Why was the broom late? It swept in!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What did the computer keep freezing? It left its Windows open!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a pile of cats? A meowtain!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why did the computer go to the doctor? It had a virus!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you call a fish with no eyes? Fsh!",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "Why was the math book sad? Because it had too many problems.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the coffee file a police report? It got mugged!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the chicken cross the playground? To get to the other slide!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the picture go to jail? Because it was framed!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the coffee file a police report? It got mugged!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call a pile of cats? A meowtain!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the picture go to jail? Because it was framed!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call an alligator in a vest? An investigator!",
    "Why was the broom late? It swept in!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the picture go to jail? Because it was framed!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a fake noodle? An impasta!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why was the broom late? It swept in!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call a pile of cats? A meowtain!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a fake noodle? An impasta!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why was the broom late? It swept in!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call a fish with no eyes? Fsh!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why was the broom late? It swept in!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call a fake noodle? An impasta!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What did the computer go to the doctor? It had a virus!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why was the broom late? It swept in!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the coffee file a police report? It got mugged!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a pile of cats? A meowtain!",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did the computer go to the doctor? Because it had a virus!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call a fake noodle? An impasta!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why was the broom late? It swept in!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a pile of cats? A meowtain!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the computer go to the doctor? Because it had a virus!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call a fish that practices medicine? A sturgeon!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a fake noodle? An impasta!",
    "What do you call a pile of cats? A meowtain!",
    "What do you call an alligator in a vest? An investigator!",
    "Why was the broom late? It swept in!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a fish with no eyes? Fsh!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a factory that makes good products? A satisfactory!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the chicken join a band? Because it had the drumsticks!",
    "What do you call a fake noodle? An impasta!",
    "Why was the broom late? It swept in!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call an alligator in a vest? An investigator!",
    "What did the computer go to the doctor? Because it had a virus!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why was the broom late? It swept in!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a pile of cats? A meowtain!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a fake noodle? An impasta!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why was the broom late? It swept in!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the coffee file a police report? It got mugged!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "What do you call a fake noodle? An impasta!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What did the computer go to the doctor? Because it had a virus!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why was the broom late? It swept in!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a fish with no eyes? Fsh!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a fake noodle? An impasta!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What did the computer go to the doctor? Because it had a virus!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a pile of cats? A meowtain!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the coffee file a police report? It got mugged!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why was the math book sad? Because it had too many problems.",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call a fake noodle? An impasta!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman and a dog? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a pile of cats? A meowtain!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why was the broom late? It swept in!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a fake noodle? An impasta!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why was the math book sad? Because it had too many problems.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why was the broom late? It swept in!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a fake noodle? An impasta!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why was the math book sad? Because it had too many problems.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a pile of cats? A meowtain!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the coffee file a police report? It got mugged!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a fake noodle? An impasta!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What did the chicken join a band? Because it had the drumsticks!",
    "Why was the broom late? It swept in!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the computer go to the doctor? Because it had a virus!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why was the broom late? It swept in!",
    "What do you call a fish that practices medicine? A sturgeon!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a fake noodle? An impasta!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a fish with no eyes? Fsh!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why was the math book sad? Because it had too many problems.",
    "What did the coffee file a police report? It got mugged!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a fake noodle? An impasta!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a pile of cats? A meowtain!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the coffee file a police report? It got mugged!",
    "What do you call an alligator in a vest? An investigator!",
    "Why was the broom late? It swept in!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What did the computer go to the doctor? Because it had a virus!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call a pile of cats? A meowtain!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a fake noodle? An impasta!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call an alligator in a vest? An investigator!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the computer go to the doctor? Because it had a virus!",
    "What do you call a factory that makes good products? A satisfactory!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What did the coffee file a police report? It got mugged!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a joke with a rhetorical question?",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the computer go to the doctor? Because it had a virus!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a fake noodle? An impasta!",
    "What do you call a pile of cats? A meowtain!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why was the math book sad? Because it had too many problems.",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What do you call an alligator in a vest? An investigator!",
    "Why was the broom late? It swept in!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a fake noodle? An impasta!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the coffee file a police report? It got mugged!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What did the computer go to the doctor? Because it had a virus!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a fake noodle? An impasta!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a pile of cats? A meowtain!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you call a fake noodle? An impasta!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What do you call a pile of cats? A meowtain!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What did the computer go to the doctor? Because it had a virus!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the coffee file a police report? It got mugged!",
    "What do you call an alligator in a vest? An investigator!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What do you call a fake noodle? An impasta!",
    "What do you call a fish with no eyes? Fsh!",
    "What do you get when you cross a joke with a rhetorical question?",
    "What do you call a pile of cats? A meowtain!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What do you get when you cross a snowman with a dog? Frostbite!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did the computer go to the doctor? Because it had a virus!",
    "What do you call a factory that makes good products? A satisfactory!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get when you cross a joke with a rhetorical question?"
]